// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: quizzes/generic_message.proto

package quizzes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_quizzes_generic_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_generic_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_quizzes_generic_message_proto_rawDescGZIP(), []int{0}
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_quizzes_generic_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_generic_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_quizzes_generic_message_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StringMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMessage) Reset() {
	*x = StringMessage{}
	mi := &file_quizzes_generic_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMessage) ProtoMessage() {}

func (x *StringMessage) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_generic_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMessage.ProtoReflect.Descriptor instead.
func (*StringMessage) Descriptor() ([]byte, []int) {
	return file_quizzes_generic_message_proto_rawDescGZIP(), []int{2}
}

func (x *StringMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BoolMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsTrue        bool                   `protobuf:"varint,1,opt,name=is_true,json=isTrue,proto3" json:"is_true,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolMessage) Reset() {
	*x = BoolMessage{}
	mi := &file_quizzes_generic_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolMessage) ProtoMessage() {}

func (x *BoolMessage) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_generic_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolMessage.ProtoReflect.Descriptor instead.
func (*BoolMessage) Descriptor() ([]byte, []int) {
	return file_quizzes_generic_message_proto_rawDescGZIP(), []int{3}
}

func (x *BoolMessage) GetIsTrue() bool {
	if x != nil {
		return x.IsTrue
	}
	return false
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=order,proto3" json:"order,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_quizzes_generic_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_generic_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_quizzes_generic_message_proto_rawDescGZIP(), []int{4}
}

func (x *Pagination) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Pagination) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *Pagination) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Pagination) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

var File_quizzes_generic_message_proto protoreflect.FileDescriptor

const file_quizzes_generic_message_proto_rawDesc = "" +
	"\n" +
	"\x1dquizzes/generic_message.proto\x12\aquizzes\"\x0e\n" +
	"\fEmptyMessage\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\")\n" +
	"\rStringMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"&\n" +
	"\vBoolMessage\x12\x17\n" +
	"\ais_true\x18\x01 \x01(\bR\x06isTrue\"~\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x14\n" +
	"\x05order\x18\x04 \x01(\tR\x05order\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sortB\x14Z\x12pb/quizzes;quizzesb\x06proto3"

var (
	file_quizzes_generic_message_proto_rawDescOnce sync.Once
	file_quizzes_generic_message_proto_rawDescData []byte
)

func file_quizzes_generic_message_proto_rawDescGZIP() []byte {
	file_quizzes_generic_message_proto_rawDescOnce.Do(func() {
		file_quizzes_generic_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quizzes_generic_message_proto_rawDesc), len(file_quizzes_generic_message_proto_rawDesc)))
	})
	return file_quizzes_generic_message_proto_rawDescData
}

var file_quizzes_generic_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_quizzes_generic_message_proto_goTypes = []any{
	(*EmptyMessage)(nil),  // 0: quizzes.EmptyMessage
	(*Id)(nil),            // 1: quizzes.Id
	(*StringMessage)(nil), // 2: quizzes.StringMessage
	(*BoolMessage)(nil),   // 3: quizzes.BoolMessage
	(*Pagination)(nil),    // 4: quizzes.Pagination
}
var file_quizzes_generic_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_quizzes_generic_message_proto_init() }
func file_quizzes_generic_message_proto_init() {
	if File_quizzes_generic_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quizzes_generic_message_proto_rawDesc), len(file_quizzes_generic_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quizzes_generic_message_proto_goTypes,
		DependencyIndexes: file_quizzes_generic_message_proto_depIdxs,
		MessageInfos:      file_quizzes_generic_message_proto_msgTypes,
	}.Build()
	File_quizzes_generic_message_proto = out.File
	file_quizzes_generic_message_proto_goTypes = nil
	file_quizzes_generic_message_proto_depIdxs = nil
}
