// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: quizzes/question_input.proto

package quizzes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionUpdateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StorageId     string                 `protobuf:"bytes,4,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	AnswerId      string                 `protobuf:"bytes,5,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	Option        []*OptionUpdateInput   `protobuf:"bytes,6,rep,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionUpdateInput) Reset() {
	*x = QuestionUpdateInput{}
	mi := &file_quizzes_question_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionUpdateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionUpdateInput) ProtoMessage() {}

func (x *QuestionUpdateInput) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_question_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionUpdateInput.ProtoReflect.Descriptor instead.
func (*QuestionUpdateInput) Descriptor() ([]byte, []int) {
	return file_quizzes_question_input_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionUpdateInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuestionUpdateInput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuestionUpdateInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QuestionUpdateInput) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *QuestionUpdateInput) GetAnswerId() string {
	if x != nil {
		return x.AnswerId
	}
	return ""
}

func (x *QuestionUpdateInput) GetOption() []*OptionUpdateInput {
	if x != nil {
		return x.Option
	}
	return nil
}

type QuestionAnswerInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuestionId    string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	AnswerId      string                 `protobuf:"bytes,2,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionAnswerInput) Reset() {
	*x = QuestionAnswerInput{}
	mi := &file_quizzes_question_input_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionAnswerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionAnswerInput) ProtoMessage() {}

func (x *QuestionAnswerInput) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_question_input_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionAnswerInput.ProtoReflect.Descriptor instead.
func (*QuestionAnswerInput) Descriptor() ([]byte, []int) {
	return file_quizzes_question_input_proto_rawDescGZIP(), []int{1}
}

func (x *QuestionAnswerInput) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *QuestionAnswerInput) GetAnswerId() string {
	if x != nil {
		return x.AnswerId
	}
	return ""
}

type QuestionCreateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StorageId     string                 `protobuf:"bytes,3,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Option        []*OptionCreateInput   `protobuf:"bytes,4,rep,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionCreateInput) Reset() {
	*x = QuestionCreateInput{}
	mi := &file_quizzes_question_input_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionCreateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionCreateInput) ProtoMessage() {}

func (x *QuestionCreateInput) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_question_input_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionCreateInput.ProtoReflect.Descriptor instead.
func (*QuestionCreateInput) Descriptor() ([]byte, []int) {
	return file_quizzes_question_input_proto_rawDescGZIP(), []int{2}
}

func (x *QuestionCreateInput) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuestionCreateInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QuestionCreateInput) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *QuestionCreateInput) GetOption() []*OptionCreateInput {
	if x != nil {
		return x.Option
	}
	return nil
}

var File_quizzes_question_input_proto protoreflect.FileDescriptor

const file_quizzes_question_input_proto_rawDesc = "" +
	"\n" +
	"\x1cquizzes/question_input.proto\x12\aquizzes\x1a\x1aquizzes/option_input.proto\"\xcd\x01\n" +
	"\x13QuestionUpdateInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x04 \x01(\tR\tstorageId\x12\x1b\n" +
	"\tanswer_id\x18\x05 \x01(\tR\banswerId\x122\n" +
	"\x06option\x18\x06 \x03(\v2\x1a.quizzes.OptionUpdateInputR\x06option\"S\n" +
	"\x13QuestionAnswerInput\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x1b\n" +
	"\tanswer_id\x18\x02 \x01(\tR\banswerId\"\xa0\x01\n" +
	"\x13QuestionCreateInput\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x03 \x01(\tR\tstorageId\x122\n" +
	"\x06option\x18\x04 \x03(\v2\x1a.quizzes.OptionCreateInputR\x06optionB\x14Z\x12pb/quizzes;quizzesb\x06proto3"

var (
	file_quizzes_question_input_proto_rawDescOnce sync.Once
	file_quizzes_question_input_proto_rawDescData []byte
)

func file_quizzes_question_input_proto_rawDescGZIP() []byte {
	file_quizzes_question_input_proto_rawDescOnce.Do(func() {
		file_quizzes_question_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quizzes_question_input_proto_rawDesc), len(file_quizzes_question_input_proto_rawDesc)))
	})
	return file_quizzes_question_input_proto_rawDescData
}

var file_quizzes_question_input_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_quizzes_question_input_proto_goTypes = []any{
	(*QuestionUpdateInput)(nil), // 0: quizzes.QuestionUpdateInput
	(*QuestionAnswerInput)(nil), // 1: quizzes.QuestionAnswerInput
	(*QuestionCreateInput)(nil), // 2: quizzes.QuestionCreateInput
	(*OptionUpdateInput)(nil),   // 3: quizzes.OptionUpdateInput
	(*OptionCreateInput)(nil),   // 4: quizzes.OptionCreateInput
}
var file_quizzes_question_input_proto_depIdxs = []int32{
	3, // 0: quizzes.QuestionUpdateInput.option:type_name -> quizzes.OptionUpdateInput
	4, // 1: quizzes.QuestionCreateInput.option:type_name -> quizzes.OptionCreateInput
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_quizzes_question_input_proto_init() }
func file_quizzes_question_input_proto_init() {
	if File_quizzes_question_input_proto != nil {
		return
	}
	file_quizzes_option_input_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quizzes_question_input_proto_rawDesc), len(file_quizzes_question_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quizzes_question_input_proto_goTypes,
		DependencyIndexes: file_quizzes_question_input_proto_depIdxs,
		MessageInfos:      file_quizzes_question_input_proto_msgTypes,
	}.Build()
	File_quizzes_question_input_proto = out.File
	file_quizzes_question_input_proto_goTypes = nil
	file_quizzes_question_input_proto_depIdxs = nil
}
