// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: quizzes/question_message.proto

package quizzes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StorageId     string                 `protobuf:"bytes,4,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	AnswerId      string                 `protobuf:"bytes,5,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Option        []*Option              `protobuf:"bytes,9,rep,name=option,proto3" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_quizzes_question_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_question_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_quizzes_question_message_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Question) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Question) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *Question) GetAnswerId() string {
	if x != nil {
		return x.AnswerId
	}
	return ""
}

func (x *Question) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Question) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Question) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Question) GetOption() []*Option {
	if x != nil {
		return x.Option
	}
	return nil
}

type QuestionAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Question      *Question              `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	AnswerId      string                 `protobuf:"bytes,3,opt,name=answer_id,json=answerId,proto3" json:"answer_id,omitempty"`
	IsCorrect     bool                   `protobuf:"varint,4,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionAnswer) Reset() {
	*x = QuestionAnswer{}
	mi := &file_quizzes_question_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionAnswer) ProtoMessage() {}

func (x *QuestionAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_question_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionAnswer.ProtoReflect.Descriptor instead.
func (*QuestionAnswer) Descriptor() ([]byte, []int) {
	return file_quizzes_question_message_proto_rawDescGZIP(), []int{1}
}

func (x *QuestionAnswer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuestionAnswer) GetQuestion() *Question {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *QuestionAnswer) GetAnswerId() string {
	if x != nil {
		return x.AnswerId
	}
	return ""
}

func (x *QuestionAnswer) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *QuestionAnswer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_quizzes_question_message_proto protoreflect.FileDescriptor

const file_quizzes_question_message_proto_rawDesc = "" +
	"\n" +
	"\x1equizzes/question_message.proto\x12\aquizzes\x1a\x1cquizzes/option_message.proto\"\x94\x02\n" +
	"\bQuestion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x04 \x01(\tR\tstorageId\x12\x1b\n" +
	"\tanswer_id\x18\x05 \x01(\tR\banswerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\x12'\n" +
	"\x06option\x18\t \x03(\v2\x0f.quizzes.OptionR\x06option\"\xaa\x01\n" +
	"\x0eQuestionAnswer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12-\n" +
	"\bquestion\x18\x02 \x01(\v2\x11.quizzes.QuestionR\bquestion\x12\x1b\n" +
	"\tanswer_id\x18\x03 \x01(\tR\banswerId\x12\x1d\n" +
	"\n" +
	"is_correct\x18\x04 \x01(\bR\tisCorrect\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAtB\x14Z\x12pb/quizzes;quizzesb\x06proto3"

var (
	file_quizzes_question_message_proto_rawDescOnce sync.Once
	file_quizzes_question_message_proto_rawDescData []byte
)

func file_quizzes_question_message_proto_rawDescGZIP() []byte {
	file_quizzes_question_message_proto_rawDescOnce.Do(func() {
		file_quizzes_question_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quizzes_question_message_proto_rawDesc), len(file_quizzes_question_message_proto_rawDesc)))
	})
	return file_quizzes_question_message_proto_rawDescData
}

var file_quizzes_question_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_quizzes_question_message_proto_goTypes = []any{
	(*Question)(nil),       // 0: quizzes.Question
	(*QuestionAnswer)(nil), // 1: quizzes.QuestionAnswer
	(*Option)(nil),         // 2: quizzes.Option
}
var file_quizzes_question_message_proto_depIdxs = []int32{
	2, // 0: quizzes.Question.option:type_name -> quizzes.Option
	0, // 1: quizzes.QuestionAnswer.question:type_name -> quizzes.Question
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_quizzes_question_message_proto_init() }
func file_quizzes_question_message_proto_init() {
	if File_quizzes_question_message_proto != nil {
		return
	}
	file_quizzes_option_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quizzes_question_message_proto_rawDesc), len(file_quizzes_question_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quizzes_question_message_proto_goTypes,
		DependencyIndexes: file_quizzes_question_message_proto_depIdxs,
		MessageInfos:      file_quizzes_question_message_proto_msgTypes,
	}.Build()
	File_quizzes_question_message_proto = out.File
	file_quizzes_question_message_proto_goTypes = nil
	file_quizzes_question_message_proto_depIdxs = nil
}
