// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.20.3
// source: quizzes/quiz_message.proto

package quizzes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quiz struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectClassId string      `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	TopicSubjectId string      `protobuf:"bytes,3,opt,name=topic_subject_id,json=topicSubjectId,proto3" json:"topic_subject_id,omitempty"`
	Name           string      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string      `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	EndDate        string      `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CreatedAt      string      `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string      `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy      string      `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Question       []*Question `protobuf:"bytes,10,rep,name=question,proto3" json:"question,omitempty"`
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quizzes_quiz_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_message_proto_rawDescGZIP(), []int{0}
}

func (x *Quiz) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quiz) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *Quiz) GetTopicSubjectId() string {
	if x != nil {
		return x.TopicSubjectId
	}
	return ""
}

func (x *Quiz) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Quiz) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Quiz) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Quiz) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Quiz) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Quiz) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Quiz) GetQuestion() []*Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type QuizAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quiz           *Quiz             `protobuf:"bytes,2,opt,name=quiz,proto3" json:"quiz,omitempty"`
	StudentId      string            `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Score          int32             `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	CreatedAt      string            `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	QuestionAnswer []*QuestionAnswer `protobuf:"bytes,6,rep,name=question_answer,json=questionAnswer,proto3" json:"question_answer,omitempty"`
}

func (x *QuizAnswer) Reset() {
	*x = QuizAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quizzes_quiz_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuizAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizAnswer) ProtoMessage() {}

func (x *QuizAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizAnswer.ProtoReflect.Descriptor instead.
func (*QuizAnswer) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_message_proto_rawDescGZIP(), []int{1}
}

func (x *QuizAnswer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizAnswer) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

func (x *QuizAnswer) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *QuizAnswer) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuizAnswer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QuizAnswer) GetQuestionAnswer() []*QuestionAnswer {
	if x != nil {
		return x.QuestionAnswer
	}
	return nil
}

type GetResultQuizInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizId    string `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	StudentId string `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
}

func (x *GetResultQuizInput) Reset() {
	*x = GetResultQuizInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quizzes_quiz_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResultQuizInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultQuizInput) ProtoMessage() {}

func (x *GetResultQuizInput) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultQuizInput.ProtoReflect.Descriptor instead.
func (*GetResultQuizInput) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_message_proto_rawDescGZIP(), []int{2}
}

func (x *GetResultQuizInput) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *GetResultQuizInput) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GetResultQuizOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuizResults []*QuizResult `protobuf:"bytes,1,rep,name=quiz_results,json=quizResults,proto3" json:"quiz_results,omitempty"`
}

func (x *GetResultQuizOutput) Reset() {
	*x = GetResultQuizOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quizzes_quiz_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResultQuizOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultQuizOutput) ProtoMessage() {}

func (x *GetResultQuizOutput) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultQuizOutput.ProtoReflect.Descriptor instead.
func (*GetResultQuizOutput) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetResultQuizOutput) GetQuizResults() []*QuizResult {
	if x != nil {
		return x.QuizResults
	}
	return nil
}

type QuizResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StudentAnswerQuizzesId string `protobuf:"bytes,1,opt,name=student_answer_quizzes_id,json=studentAnswerQuizzesId,proto3" json:"student_answer_quizzes_id,omitempty"`
	StudentQuizzesId       string `protobuf:"bytes,2,opt,name=student_quizzes_id,json=studentQuizzesId,proto3" json:"student_quizzes_id,omitempty"`
	Name                   string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description            string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Title                  string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	IsCorrect              bool   `protobuf:"varint,6,opt,name=is_correct,json=isCorrect,proto3" json:"is_correct,omitempty"`
	Score                  int32  `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *QuizResult) Reset() {
	*x = QuizResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quizzes_quiz_message_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuizResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizResult) ProtoMessage() {}

func (x *QuizResult) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_message_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizResult.ProtoReflect.Descriptor instead.
func (*QuizResult) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_message_proto_rawDescGZIP(), []int{4}
}

func (x *QuizResult) GetStudentAnswerQuizzesId() string {
	if x != nil {
		return x.StudentAnswerQuizzesId
	}
	return ""
}

func (x *QuizResult) GetStudentQuizzesId() string {
	if x != nil {
		return x.StudentQuizzesId
	}
	return ""
}

func (x *QuizResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuizResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QuizResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *QuizResult) GetIsCorrect() bool {
	if x != nil {
		return x.IsCorrect
	}
	return false
}

func (x *QuizResult) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_quizzes_quiz_message_proto protoreflect.FileDescriptor

var file_quizzes_quiz_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x71, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x71, 0x75,
	0x69, 0x7a, 0x7a, 0x65, 0x73, 0x1a, 0x1e, 0x71, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x2f, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc7, 0x02, 0x0a, 0x04, 0x51, 0x75, 0x69, 0x7a, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28,
	0x0a, 0x10, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x5f, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x53, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79,
	0x12, 0x2d, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x2e, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0xd5, 0x01, 0x0a, 0x0a, 0x51, 0x75, 0x69, 0x7a, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21,
	0x0a, 0x04, 0x71, 0x75, 0x69, 0x7a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x71,
	0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x2e, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x04, 0x71, 0x75, 0x69,
	0x7a, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x40, 0x0a, 0x0f, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x71, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x0e, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x71, 0x75, 0x69, 0x7a, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x71, 0x75, 0x69, 0x7a, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x36, 0x0a, 0x0c,
	0x71, 0x75, 0x69, 0x7a, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x71, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x2e, 0x51, 0x75, 0x69,
	0x7a, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0b, 0x71, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x22, 0xf6, 0x01, 0x0a, 0x0a, 0x51, 0x75, 0x69, 0x7a, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x39, 0x0a, 0x19, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x61,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x5f, 0x71, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x51, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x49, 0x64, 0x12, 0x2c,
	0x0a, 0x12, 0x73, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x5f, 0x71, 0x75, 0x69, 0x7a, 0x7a, 0x65,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x74, 0x75, 0x64,
	0x65, 0x6e, 0x74, 0x51, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x63,
	0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73,
	0x43, 0x6f, 0x72, 0x72, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x42, 0x14, 0x5a,
	0x12, 0x70, 0x62, 0x2f, 0x71, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x3b, 0x71, 0x75, 0x69, 0x7a,
	0x7a, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quizzes_quiz_message_proto_rawDescOnce sync.Once
	file_quizzes_quiz_message_proto_rawDescData = file_quizzes_quiz_message_proto_rawDesc
)

func file_quizzes_quiz_message_proto_rawDescGZIP() []byte {
	file_quizzes_quiz_message_proto_rawDescOnce.Do(func() {
		file_quizzes_quiz_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_quizzes_quiz_message_proto_rawDescData)
	})
	return file_quizzes_quiz_message_proto_rawDescData
}

var file_quizzes_quiz_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_quizzes_quiz_message_proto_goTypes = []any{
	(*Quiz)(nil),                // 0: quizzes.Quiz
	(*QuizAnswer)(nil),          // 1: quizzes.QuizAnswer
	(*GetResultQuizInput)(nil),  // 2: quizzes.GetResultQuizInput
	(*GetResultQuizOutput)(nil), // 3: quizzes.GetResultQuizOutput
	(*QuizResult)(nil),          // 4: quizzes.QuizResult
	(*Question)(nil),            // 5: quizzes.Question
	(*QuestionAnswer)(nil),      // 6: quizzes.QuestionAnswer
}
var file_quizzes_quiz_message_proto_depIdxs = []int32{
	5, // 0: quizzes.Quiz.question:type_name -> quizzes.Question
	0, // 1: quizzes.QuizAnswer.quiz:type_name -> quizzes.Quiz
	6, // 2: quizzes.QuizAnswer.question_answer:type_name -> quizzes.QuestionAnswer
	4, // 3: quizzes.GetResultQuizOutput.quiz_results:type_name -> quizzes.QuizResult
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_quizzes_quiz_message_proto_init() }
func file_quizzes_quiz_message_proto_init() {
	if File_quizzes_quiz_message_proto != nil {
		return
	}
	file_quizzes_question_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_quizzes_quiz_message_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Quiz); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quizzes_quiz_message_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*QuizAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quizzes_quiz_message_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetResultQuizInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quizzes_quiz_message_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetResultQuizOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_quizzes_quiz_message_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*QuizResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quizzes_quiz_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quizzes_quiz_message_proto_goTypes,
		DependencyIndexes: file_quizzes_quiz_message_proto_depIdxs,
		MessageInfos:      file_quizzes_quiz_message_proto_msgTypes,
	}.Build()
	File_quizzes_quiz_message_proto = out.File
	file_quizzes_quiz_message_proto_rawDesc = nil
	file_quizzes_quiz_message_proto_goTypes = nil
	file_quizzes_quiz_message_proto_depIdxs = nil
}
