// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: quizzes/quiz_service.proto

package quizzes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_quizzes_quiz_service_proto protoreflect.FileDescriptor

const file_quizzes_quiz_service_proto_rawDesc = "" +
	"\n" +
	"\x1aquizzes/quiz_service.proto\x12\aquizzes\x1a\x1aquizzes/quiz_message.proto\x1a\x18quizzes/quiz_input.proto\x1a\x1dquizzes/generic_message.proto2\x84\x03\n" +
	"\aQuizzes\x123\n" +
	"\x06Update\x12\x18.quizzes.QuizUpdateInput\x1a\r.quizzes.Quiz\"\x00\x129\n" +
	"\x06Answer\x12\x18.quizzes.QuizAnswerInput\x1a\x13.quizzes.QuizAnswer\"\x00\x12#\n" +
	"\x03Get\x12\v.quizzes.Id\x1a\r.quizzes.Quiz\"\x00\x12C\n" +
	"\rGetResultQuiz\x12\x1b.quizzes.GetResultQuizInput\x1a\x13.quizzes.QuizAnswer\"\x00\x12-\n" +
	"\x06Delete\x12\v.quizzes.Id\x1a\x14.quizzes.BoolMessage\"\x00\x123\n" +
	"\x06Create\x12\x18.quizzes.QuizCreateInput\x1a\r.quizzes.Quiz\"\x00\x12;\n" +
	"\x12ListScoresByQuizId\x12\v.quizzes.Id\x1a\x16.quizzes.QuizScoreList\"\x00B\x14Z\x12pb/quizzes;quizzesb\x06proto3"

var file_quizzes_quiz_service_proto_goTypes = []any{
	(*QuizUpdateInput)(nil),    // 0: quizzes.QuizUpdateInput
	(*QuizAnswerInput)(nil),    // 1: quizzes.QuizAnswerInput
	(*Id)(nil),                 // 2: quizzes.Id
	(*GetResultQuizInput)(nil), // 3: quizzes.GetResultQuizInput
	(*QuizCreateInput)(nil),    // 4: quizzes.QuizCreateInput
	(*Quiz)(nil),               // 5: quizzes.Quiz
	(*QuizAnswer)(nil),         // 6: quizzes.QuizAnswer
	(*BoolMessage)(nil),        // 7: quizzes.BoolMessage
	(*QuizScoreList)(nil),      // 8: quizzes.QuizScoreList
}
var file_quizzes_quiz_service_proto_depIdxs = []int32{
	0, // 0: quizzes.Quizzes.Update:input_type -> quizzes.QuizUpdateInput
	1, // 1: quizzes.Quizzes.Answer:input_type -> quizzes.QuizAnswerInput
	2, // 2: quizzes.Quizzes.Get:input_type -> quizzes.Id
	3, // 3: quizzes.Quizzes.GetResultQuiz:input_type -> quizzes.GetResultQuizInput
	2, // 4: quizzes.Quizzes.Delete:input_type -> quizzes.Id
	4, // 5: quizzes.Quizzes.Create:input_type -> quizzes.QuizCreateInput
	2, // 6: quizzes.Quizzes.ListScoresByQuizId:input_type -> quizzes.Id
	5, // 7: quizzes.Quizzes.Update:output_type -> quizzes.Quiz
	6, // 8: quizzes.Quizzes.Answer:output_type -> quizzes.QuizAnswer
	5, // 9: quizzes.Quizzes.Get:output_type -> quizzes.Quiz
	6, // 10: quizzes.Quizzes.GetResultQuiz:output_type -> quizzes.QuizAnswer
	7, // 11: quizzes.Quizzes.Delete:output_type -> quizzes.BoolMessage
	5, // 12: quizzes.Quizzes.Create:output_type -> quizzes.Quiz
	8, // 13: quizzes.Quizzes.ListScoresByQuizId:output_type -> quizzes.QuizScoreList
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_quizzes_quiz_service_proto_init() }
func file_quizzes_quiz_service_proto_init() {
	if File_quizzes_quiz_service_proto != nil {
		return
	}
	file_quizzes_quiz_message_proto_init()
	file_quizzes_quiz_input_proto_init()
	file_quizzes_generic_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quizzes_quiz_service_proto_rawDesc), len(file_quizzes_quiz_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quizzes_quiz_service_proto_goTypes,
		DependencyIndexes: file_quizzes_quiz_service_proto_depIdxs,
	}.Build()
	File_quizzes_quiz_service_proto = out.File
	file_quizzes_quiz_service_proto_goTypes = nil
	file_quizzes_quiz_service_proto_depIdxs = nil
}
