// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: quizzes/quiz_message.proto

package quizzes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Quiz struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectClassId string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	TopicSubjectId string                 `protobuf:"bytes,3,opt,name=topic_subject_id,json=topicSubjectId,proto3" json:"topic_subject_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	EndDate        string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Question       []*Question            `protobuf:"bytes,10,rep,name=question,proto3" json:"question,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Quiz) Reset() {
	*x = Quiz{}
	mi := &file_quizzes_quiz_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quiz) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quiz) ProtoMessage() {}

func (x *Quiz) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quiz.ProtoReflect.Descriptor instead.
func (*Quiz) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_message_proto_rawDescGZIP(), []int{0}
}

func (x *Quiz) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Quiz) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *Quiz) GetTopicSubjectId() string {
	if x != nil {
		return x.TopicSubjectId
	}
	return ""
}

func (x *Quiz) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Quiz) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Quiz) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Quiz) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Quiz) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Quiz) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Quiz) GetQuestion() []*Question {
	if x != nil {
		return x.Question
	}
	return nil
}

type QuizAnswer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quiz           *Quiz                  `protobuf:"bytes,2,opt,name=quiz,proto3" json:"quiz,omitempty"`
	StudentId      string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Score          int32                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	QuestionAnswer []*QuestionAnswer      `protobuf:"bytes,6,rep,name=question_answer,json=questionAnswer,proto3" json:"question_answer,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuizAnswer) Reset() {
	*x = QuizAnswer{}
	mi := &file_quizzes_quiz_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizAnswer) ProtoMessage() {}

func (x *QuizAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizAnswer.ProtoReflect.Descriptor instead.
func (*QuizAnswer) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_message_proto_rawDescGZIP(), []int{1}
}

func (x *QuizAnswer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizAnswer) GetQuiz() *Quiz {
	if x != nil {
		return x.Quiz
	}
	return nil
}

func (x *QuizAnswer) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *QuizAnswer) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuizAnswer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *QuizAnswer) GetQuestionAnswer() []*QuestionAnswer {
	if x != nil {
		return x.QuestionAnswer
	}
	return nil
}

type GetResultQuizInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuizId        string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResultQuizInput) Reset() {
	*x = GetResultQuizInput{}
	mi := &file_quizzes_quiz_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResultQuizInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultQuizInput) ProtoMessage() {}

func (x *GetResultQuizInput) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultQuizInput.ProtoReflect.Descriptor instead.
func (*GetResultQuizInput) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_message_proto_rawDescGZIP(), []int{2}
}

func (x *GetResultQuizInput) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *GetResultQuizInput) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type QuizScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentQuizId string                 `protobuf:"bytes,1,opt,name=student_quiz_id,json=studentQuizId,proto3" json:"student_quiz_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Score         int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizScore) Reset() {
	*x = QuizScore{}
	mi := &file_quizzes_quiz_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizScore) ProtoMessage() {}

func (x *QuizScore) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizScore.ProtoReflect.Descriptor instead.
func (*QuizScore) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_message_proto_rawDescGZIP(), []int{3}
}

func (x *QuizScore) GetStudentQuizId() string {
	if x != nil {
		return x.StudentQuizId
	}
	return ""
}

func (x *QuizScore) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *QuizScore) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QuizScore) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type QuizScoreList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*QuizScore           `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizScoreList) Reset() {
	*x = QuizScoreList{}
	mi := &file_quizzes_quiz_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizScoreList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizScoreList) ProtoMessage() {}

func (x *QuizScoreList) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizScoreList.ProtoReflect.Descriptor instead.
func (*QuizScoreList) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_message_proto_rawDescGZIP(), []int{4}
}

func (x *QuizScoreList) GetScores() []*QuizScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_quizzes_quiz_message_proto protoreflect.FileDescriptor

const file_quizzes_quiz_message_proto_rawDesc = "" +
	"\n" +
	"\x1aquizzes/quiz_message.proto\x12\aquizzes\x1a\x1equizzes/question_message.proto\"\xc7\x02\n" +
	"\x04Quiz\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\x12(\n" +
	"\x10topic_subject_id\x18\x03 \x01(\tR\x0etopicSubjectId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\tR\tupdatedBy\x12-\n" +
	"\bquestion\x18\n" +
	" \x03(\v2\x11.quizzes.QuestionR\bquestion\"\xd5\x01\n" +
	"\n" +
	"QuizAnswer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\x04quiz\x18\x02 \x01(\v2\r.quizzes.QuizR\x04quiz\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x05R\x05score\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12@\n" +
	"\x0fquestion_answer\x18\x06 \x03(\v2\x17.quizzes.QuestionAnswerR\x0equestionAnswer\"L\n" +
	"\x12GetResultQuizInput\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\"\x87\x01\n" +
	"\tQuizScore\x12&\n" +
	"\x0fstudent_quiz_id\x18\x01 \x01(\tR\rstudentQuizId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\";\n" +
	"\rQuizScoreList\x12*\n" +
	"\x06scores\x18\x01 \x03(\v2\x12.quizzes.QuizScoreR\x06scoresB\x14Z\x12pb/quizzes;quizzesb\x06proto3"

var (
	file_quizzes_quiz_message_proto_rawDescOnce sync.Once
	file_quizzes_quiz_message_proto_rawDescData []byte
)

func file_quizzes_quiz_message_proto_rawDescGZIP() []byte {
	file_quizzes_quiz_message_proto_rawDescOnce.Do(func() {
		file_quizzes_quiz_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quizzes_quiz_message_proto_rawDesc), len(file_quizzes_quiz_message_proto_rawDesc)))
	})
	return file_quizzes_quiz_message_proto_rawDescData
}

var file_quizzes_quiz_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_quizzes_quiz_message_proto_goTypes = []any{
	(*Quiz)(nil),               // 0: quizzes.Quiz
	(*QuizAnswer)(nil),         // 1: quizzes.QuizAnswer
	(*GetResultQuizInput)(nil), // 2: quizzes.GetResultQuizInput
	(*QuizScore)(nil),          // 3: quizzes.QuizScore
	(*QuizScoreList)(nil),      // 4: quizzes.QuizScoreList
	(*Question)(nil),           // 5: quizzes.Question
	(*QuestionAnswer)(nil),     // 6: quizzes.QuestionAnswer
}
var file_quizzes_quiz_message_proto_depIdxs = []int32{
	5, // 0: quizzes.Quiz.question:type_name -> quizzes.Question
	0, // 1: quizzes.QuizAnswer.quiz:type_name -> quizzes.Quiz
	6, // 2: quizzes.QuizAnswer.question_answer:type_name -> quizzes.QuestionAnswer
	3, // 3: quizzes.QuizScoreList.scores:type_name -> quizzes.QuizScore
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_quizzes_quiz_message_proto_init() }
func file_quizzes_quiz_message_proto_init() {
	if File_quizzes_quiz_message_proto != nil {
		return
	}
	file_quizzes_question_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quizzes_quiz_message_proto_rawDesc), len(file_quizzes_quiz_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quizzes_quiz_message_proto_goTypes,
		DependencyIndexes: file_quizzes_quiz_message_proto_depIdxs,
		MessageInfos:      file_quizzes_quiz_message_proto_msgTypes,
	}.Build()
	File_quizzes_quiz_message_proto = out.File
	file_quizzes_quiz_message_proto_goTypes = nil
	file_quizzes_quiz_message_proto_depIdxs = nil
}
