// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: quizzes/quiz_input.proto

package quizzes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuizUpdateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	EndDate       string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Question      []*QuestionUpdateInput `protobuf:"bytes,5,rep,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuizUpdateInput) Reset() {
	*x = QuizUpdateInput{}
	mi := &file_quizzes_quiz_input_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizUpdateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizUpdateInput) ProtoMessage() {}

func (x *QuizUpdateInput) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_input_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizUpdateInput.ProtoReflect.Descriptor instead.
func (*QuizUpdateInput) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_input_proto_rawDescGZIP(), []int{0}
}

func (x *QuizUpdateInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *QuizUpdateInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuizUpdateInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QuizUpdateInput) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *QuizUpdateInput) GetQuestion() []*QuestionUpdateInput {
	if x != nil {
		return x.Question
	}
	return nil
}

type QuizAnswerInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuizId         string                 `protobuf:"bytes,1,opt,name=quiz_id,json=quizId,proto3" json:"quiz_id,omitempty"`
	QuestionAnswer []*QuestionAnswerInput `protobuf:"bytes,2,rep,name=question_answer,json=questionAnswer,proto3" json:"question_answer,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuizAnswerInput) Reset() {
	*x = QuizAnswerInput{}
	mi := &file_quizzes_quiz_input_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizAnswerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizAnswerInput) ProtoMessage() {}

func (x *QuizAnswerInput) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_input_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizAnswerInput.ProtoReflect.Descriptor instead.
func (*QuizAnswerInput) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_input_proto_rawDescGZIP(), []int{1}
}

func (x *QuizAnswerInput) GetQuizId() string {
	if x != nil {
		return x.QuizId
	}
	return ""
}

func (x *QuizAnswerInput) GetQuestionAnswer() []*QuestionAnswerInput {
	if x != nil {
		return x.QuestionAnswer
	}
	return nil
}

type QuizCreateInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubjectClassId string                 `protobuf:"bytes,1,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	TopicSubjectId string                 `protobuf:"bytes,2,opt,name=topic_subject_id,json=topicSubjectId,proto3" json:"topic_subject_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	EndDate        string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Question       []*QuestionCreateInput `protobuf:"bytes,6,rep,name=question,proto3" json:"question,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QuizCreateInput) Reset() {
	*x = QuizCreateInput{}
	mi := &file_quizzes_quiz_input_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuizCreateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuizCreateInput) ProtoMessage() {}

func (x *QuizCreateInput) ProtoReflect() protoreflect.Message {
	mi := &file_quizzes_quiz_input_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuizCreateInput.ProtoReflect.Descriptor instead.
func (*QuizCreateInput) Descriptor() ([]byte, []int) {
	return file_quizzes_quiz_input_proto_rawDescGZIP(), []int{2}
}

func (x *QuizCreateInput) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *QuizCreateInput) GetTopicSubjectId() string {
	if x != nil {
		return x.TopicSubjectId
	}
	return ""
}

func (x *QuizCreateInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuizCreateInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *QuizCreateInput) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *QuizCreateInput) GetQuestion() []*QuestionCreateInput {
	if x != nil {
		return x.Question
	}
	return nil
}

var File_quizzes_quiz_input_proto protoreflect.FileDescriptor

const file_quizzes_quiz_input_proto_rawDesc = "" +
	"\n" +
	"\x18quizzes/quiz_input.proto\x12\aquizzes\x1a\x1cquizzes/question_input.proto\"\xac\x01\n" +
	"\x0fQuizUpdateInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\x128\n" +
	"\bquestion\x18\x05 \x03(\v2\x1c.quizzes.QuestionUpdateInputR\bquestion\"q\n" +
	"\x0fQuizAnswerInput\x12\x17\n" +
	"\aquiz_id\x18\x01 \x01(\tR\x06quizId\x12E\n" +
	"\x0fquestion_answer\x18\x02 \x03(\v2\x1c.quizzes.QuestionAnswerInputR\x0equestionAnswer\"\xf0\x01\n" +
	"\x0fQuizCreateInput\x12(\n" +
	"\x10subject_class_id\x18\x01 \x01(\tR\x0esubjectClassId\x12(\n" +
	"\x10topic_subject_id\x18\x02 \x01(\tR\x0etopicSubjectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x128\n" +
	"\bquestion\x18\x06 \x03(\v2\x1c.quizzes.QuestionCreateInputR\bquestionB\x14Z\x12pb/quizzes;quizzesb\x06proto3"

var (
	file_quizzes_quiz_input_proto_rawDescOnce sync.Once
	file_quizzes_quiz_input_proto_rawDescData []byte
)

func file_quizzes_quiz_input_proto_rawDescGZIP() []byte {
	file_quizzes_quiz_input_proto_rawDescOnce.Do(func() {
		file_quizzes_quiz_input_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quizzes_quiz_input_proto_rawDesc), len(file_quizzes_quiz_input_proto_rawDesc)))
	})
	return file_quizzes_quiz_input_proto_rawDescData
}

var file_quizzes_quiz_input_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_quizzes_quiz_input_proto_goTypes = []any{
	(*QuizUpdateInput)(nil),     // 0: quizzes.QuizUpdateInput
	(*QuizAnswerInput)(nil),     // 1: quizzes.QuizAnswerInput
	(*QuizCreateInput)(nil),     // 2: quizzes.QuizCreateInput
	(*QuestionUpdateInput)(nil), // 3: quizzes.QuestionUpdateInput
	(*QuestionAnswerInput)(nil), // 4: quizzes.QuestionAnswerInput
	(*QuestionCreateInput)(nil), // 5: quizzes.QuestionCreateInput
}
var file_quizzes_quiz_input_proto_depIdxs = []int32{
	3, // 0: quizzes.QuizUpdateInput.question:type_name -> quizzes.QuestionUpdateInput
	4, // 1: quizzes.QuizAnswerInput.question_answer:type_name -> quizzes.QuestionAnswerInput
	5, // 2: quizzes.QuizCreateInput.question:type_name -> quizzes.QuestionCreateInput
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_quizzes_quiz_input_proto_init() }
func file_quizzes_quiz_input_proto_init() {
	if File_quizzes_quiz_input_proto != nil {
		return
	}
	file_quizzes_question_input_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quizzes_quiz_input_proto_rawDesc), len(file_quizzes_quiz_input_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quizzes_quiz_input_proto_goTypes,
		DependencyIndexes: file_quizzes_quiz_input_proto_depIdxs,
		MessageInfos:      file_quizzes_quiz_input_proto_msgTypes,
	}.Build()
	File_quizzes_quiz_input_proto = out.File
	file_quizzes_quiz_input_proto_goTypes = nil
	file_quizzes_quiz_input_proto_depIdxs = nil
}
